import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'navigation_controller.dart';
import 'screens/detail_screen.dart';
import 'services/watchlist_manager.dart'; // Added the manager import
import 'screens/account_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the generated options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const FinoraApp());
}

class FinoraApp extends StatelessWidget {
  const FinoraApp({super.key});

  // Global state variables
  static String globalCurrency = "USD (\$)";
  static String globalCountryFilter = "United States";

  static String formatPrice(double baseUsdPrice) {
    double conversionRate = 1.0;
    String symbol = '\$';

    if (globalCurrency.contains('EUR')) {
      conversionRate = 0.92;
      symbol = '€';
    } else if (globalCurrency.contains('GBP')) {
      conversionRate = 0.78;
      symbol = '£';
    }

    double finalPrice = baseUsdPrice * conversionRate;
    return '$symbol${finalPrice.toStringAsFixed(2)}';
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Finora',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        brightness: Brightness.dark,
        scaffoldBackgroundColor: const Color(0xFF0B1220),
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFF131D31),
          elevation: 0,
        ),
      ),
      // AuthGate handles switching between Login and Home
      home: const AuthGate(),
      routes: {
        '/home': (context) => const NavigationController(),
        '/stock-detail': (context) => const StockDetailScreen(),
      },
    );
  }
}

// The "Traffic Controller" for your app
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // If snapshot has data, the user is signed in
        if (snapshot.hasData) {
          // Pre-initialize and sync the user's Firestore watchlist
          // right here as they step through the gateway.
          WatchlistManager.initializeWatchlist();

          return const NavigationController();
        }
        // Otherwise, show the Login/Account screen
        return const AccountScreen();
      },
    );
  }
}