import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart'; // REQUIRED: For reading verification checkpoints
import 'package:google_sign_in/google_sign_in.dart'; // REQUIRED: For the initialization plugin engine
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'navigation_controller.dart';
import 'screens/detail_screen.dart';
import 'services/watchlist_manager.dart';
import 'screens/account_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // 1. Initialize Firebase using the generated options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 2. Initialize Google Sign-In with your explicit Web Client ID parameters
  await GoogleSignIn.instance.initialize(
    serverClientId: '378713624345-c819eg5075ukmji816cg406mtn32dqn9.apps.googleusercontent.com',
  );

  runApp(const FinoraApp());
}

class FinoraApp extends StatelessWidget {
  const FinoraApp({super.key});

  // Global state variables
  static String globalCurrency = "USD (\$)";
  static String globalCountryFilter = "United States";

  static String formatPrice(double baseUsdPrice) {
    double conversionRate = 1.0;
    String symbol = '\$';

    if (globalCurrency.contains('EUR')) {
      conversionRate = 0.92;
      symbol = '€';
    } else if (globalCurrency.contains('GBP')) {
      conversionRate = 0.78;
      symbol = '£';
    }

    double finalPrice = baseUsdPrice * conversionRate;
    return '$symbol${finalPrice.toStringAsFixed(2)}';
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Finora',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        brightness: Brightness.dark,
        scaffoldBackgroundColor: const Color(0xFF0B1220),
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFF131D31),
          elevation: 0,
        ),
      ),
      // AuthGate handles switching between Login and Home
      home: const AuthGate(),
      routes: {
        '/home': (context) => const NavigationController(),
        '/stock-detail': (context) => const StockDetailScreen(),
      },
    );
  }
}

// The "Traffic Controller" for your app handling authentication and security layer routing
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // LAYER 1: If snapshot has no data, the user is completely signed out -> show gateway access
        if (!snapshot.hasData) {
          return const AccountScreen();
        }

        final user = snapshot.data!;

        // LAYER 2: Stream verification document status dynamically to handle persistent state locks
        return StreamBuilder<DocumentSnapshot>(
          stream: FirebaseFirestore.instance
              .collection('otp_verifications')
              .doc(user.uid)
              .snapshots(),
          builder: (context, otpSnapshot) {
            // Display loading blocker while retrieving server timestamps/status data
            if (!otpSnapshot.hasData) {
              return const Scaffold(
                backgroundColor: Color(0xFF0F172A),
                body: Center(child: CircularProgressIndicator(color: Color(0xFF14B8A6))),
              );
            }

            final otpData = otpSnapshot.data!.data() as Map<String, dynamic>?;
            final bool isVerified = otpData?['isVerified'] ?? false;

            // If user exists but security contract is unverified -> keep viewport locked to AccountScreen
            if (!isVerified) {
              return const AccountScreen();
            }

            // Only clear through to internal views once security token validation returns true
            WatchlistManager.initializeWatchlist();
            return const NavigationController();
          },
        );
      },
    );
  }
}